### ISSUE TITLE
'BertConfig' object has no attribute 'return_dict'

### ISSUE THREAD

**Issue by GuanNiPiShi123** [maszhongming/MatchSum#16]
When I  run the command 
CUDA_VISIBLE_DEVICES=0 python train_matching.py --mode=test --encoder=bert --save_path=./models/ --gpus=0
there is an error:
Traceback (most recent call last):
  File "train_matching.py", line 152, in <module>
    test_model(args)
  File "train_matching.py", line 111, in test_model
    tester.test()
  File "/home/gpu2/anaconda3/lib/python3.7/site-packages/fastNLP/core/tester.py", line 165, in test
    pred_dict = self._data_forward(self._predict_func, batch_x)
  File "/home/gpu2/anaconda3/lib/python3.7/site-packages/fastNLP/core/tester.py", line 213, in _data_forward
    y = self._predict_func_wrapper(**x)
  File "/home/gpu2/10T_disk/yyj/MatchSum/model.py", line 30, in forward
    out = self.encoder(text_id, attention_mask=input_mask)# last layer
  File "/home/gpu2/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gpu2/anaconda3/lib/python3.7/site-packages/transformers/modeling_bert.py", line 755, in forward
    return_dict = return_dict if return_dict is not None else self.config.use_return_dict
  File "/home/gpu2/anaconda3/lib/python3.7/site-packages/transformers/configuration_utils.py", line 203, in use_return_dict
    return self.return_dict and not self.torchscript
AttributeError: 'BertConfig' object has no attribute 'return_dict'

how to solve it ?
@maszhongming

**Comment by maszhongming** [comment]
It seems to be a problem with the transformers library. Could you please try again with the same version of transformers as mine (2.5.1)?
