### ISSUE TITLE
Unable to load pretrained model checkpoint

### ISSUE THREAD

**Issue by melvintzw** [maszhongming/MatchSum#22]
Hi, thanks so much for sharing your code and model!

I downloaded the pretrained model you provided, but ran into this error. Do you know how I can solve this issue?

```
model_path = "../../MatchSum_cnndm_roberta.ckpt"        
model = torch.load(model_path)
```
Output:

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-12-57226a25bc70> in <module>
      5 
      6 model_path = "../../MatchSum_cnndm_roberta.ckpt"
----> 7 model = torch.load(model_path)

~\fyp\env\lib\site-packages\torch\serialization.py in load(f, map_location, pickle_module, **pickle_load_args)
    527             with _open_zipfile_reader(f) as opened_zipfile:
    528                 return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
--> 529         return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
    530 
    531 

~\fyp\env\lib\site-packages\torch\serialization.py in _legacy_load(f, map_location, pickle_module, **pickle_load_args)
    700     unpickler = pickle_module.Unpickler(f, **pickle_load_args)
    701     unpickler.persistent_load = persistent_load
--> 702     result = unpickler.load()
    703 
    704     deserialized_storage_keys = pickle_module.load(f, **pickle_load_args)

ModuleNotFoundError: No module named 'model'

**Comment by XuandongZhao** [comment]
I had the same error when I want to load 'MatchSum_reddit.ckpt'
The output is:

Current model is MatchSum_reddit.ckpt
./other_pre_model/reddit/MatchSum_reddit.ckpt
/home/xuandongz/anaconda3/lib/python3.6/site-packages/torch/serialization.py:657: SourceChangeWarning: source code of class 'model.MatchSum' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
Traceback (most recent call last):
  File "train_matching.py", line 185, in <module>
    test_model(args)
  File "train_matching.py", line 105, in test_model
    model = torch.load(join(args.save_path, cur_model))
  File "/home/xuandongz/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/xuandongz/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 773, in _legacy_load
    result = unpickler.load()
ModuleNotFoundError: No module named 'transformers.modeling_bert'


When I jump to the folder where I store the pretrained models and run  "model = torch.load('MatchSum_reddit.ckpt')"

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-13-2ca04a7c5532> in <module>()
----> 1 model = torch.load('MatchSum_reddit.ckpt')

~/anaconda3/lib/python3.6/site-packages/torch/serialization.py in load(f, map_location, pickle_module, **pickle_load_args)
    591                     return torch.jit.load(f)
    592                 return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
--> 593         return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
    594 
    595 

~/anaconda3/lib/python3.6/site-packages/torch/serialization.py in _legacy_load(f, map_location, pickle_module, **pickle_load_args)
    771     unpickler = pickle_module.Unpickler(f, **pickle_load_args)
    772     unpickler.persistent_load = persistent_load
--> 773     result = unpickler.load()
    774 
    775     deserialized_storage_keys = pickle_module.load(f, **pickle_load_args)

ModuleNotFoundError: No module named 'model'

**Comment by JaniceXiong** [comment]
the same problem. Anyone fix it?

**Comment by justtuananh** [comment]
i had the same problem with you . Anyone fix it ?

**Comment by GongShuai8210** [comment]
> the same problem. Anyone fix it?

I think I solved the problem：
If you haven't run the training code once，you should:
1. Create a new file named 'roberta' in the root dir
2. Create a new file in the roberta file (suppose named  20211122)
3. put the checkpoint into  20211122
4. make sure that transformer version is 2.5.1

**Comment by mikelam92** [comment]
https://github.com/pytorch/pytorch/issues/18325
Move `model.py` to wherever you are loading the models with `torch.load` would resolve this.

**Comment by yungsinatra0** [comment]
I've moved `MatchSum_cnndm_roberta.ckpt` to the same directory as `model.py` (the directory where the whole repository was cloned) and I'm still getting the following error when trying to `torch.load` the checkpoint:

```
---------------------------------------------------------------------------

ModuleNotFoundError                       Traceback (most recent call last)

[<ipython-input-18-da29ac4b7627>](https://localhost:8080/#) in <cell line: 5>()
      3 import transformers
      4 
----> 5 torch.load('MatchSum_cnndm_roberta.ckpt')

2 frames

[/usr/local/lib/python3.10/dist-packages/torch/serialization.py](https://localhost:8080/#) in find_class(self, mod_name, name)
    846                 except KeyError:
    847                     pass
--> 848             return super().find_class(mod_name, name)
    849 
    850     def _check_container_source(container_type, source_file, original_source):

ModuleNotFoundError: No module named 'transformers.modeling_roberta'


---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------
```

`pytorch` and `transformers` were installed using `pip install -q torch transformers`

**Comment by yungsinatra0** [comment]
@mikelam92 do you have an idea what other solutions may be to this issue?
